### ISSUE TITLE
2nd version of the Library doesn't work

### ISSUE THREAD

**Issue by northern-mindset** [socialpoint-labs/sheetfu-apps-script#18] opened 2018-07-04 01:36 UTC
```var table = new Sheetfu.Table(…)```
```TypeError: (class)@5b819f2d is not a function, it is undefined.```
Indeed, v2 documentation doesn't have Table class.
https://script.google.com/macros/library/d/1N8BGDNX4N64WP4HRjsnZJNwBx2UrAbc_DPZKYwFnVxqzeJdqEJQuCBSv/2

**Comment by philippe2803** [comment] 2018-07-10 07:55
Were you able to make it work? It looks like you have not added the code as a library properly.

- Go to Resources > Libraries ...
- In the 'Add a library' placeholder, add the following key: 1N8BGDNX4N64WP4HRjsnZJNwBx2UrAbc_DPZKYwFnVxqzeJdqEJQuCBSv
 - 'Sheetfu' should be prompted. Select the last version.

Otherwise, could you please send us more code code to see where the problem could be?

**Comment by northern-mindset** [comment] 2018-07-10 10:36
For the time being I've just added code files directly into my project and
it works.

However I was adding the library exactly as you describe.

Later will try one more time and send the details.

**Comment by oshliaer** [comment] 2018-07-12 09:13
I agree the issue. It seems [Table.gs] is not published. `Sheetfu` has one method `Item()`

Switch version of the library manually
![z](https://user-images.githubusercontent.com/5027939/42623775-60b2a966-85cc-11e8-812d-b73821d0120b.png)

Version 1 works fine but not V2.

```js
function runTest() {
  logAvaibleObjects_(Sheetfu, 
    ["GridArray", "cloneObj", "Table", "getTableByName", "getTable", "Item"]
  );
}

function logAvaibleObjects_(sheetfu, shouldBe){
  var currentKeys = Object.keys(sheetfu);
  shouldBe.forEach(function(item){
    Logger.log("The method '%s' is present %s", item, !!~this.indexOf(item));
  }, currentKeys);
  Logger.log(currentKeys);
}
```

Copy the example https://docs.google.com/spreadsheets/d/1Ty7Or7uhp0YCocCEIINJ_aFIJXz7yZX5udfbBwAIu7I/copy 

It's enough?

[Table.gs]: ../blob/master/Table.gs

**Comment by sp-philippe-oger** [comment] 2018-07-12 13:27
@oshliaer thank you very much for the extra effort here.
Let me look into it now.

**Comment by oshliaer** [comment] 2018-07-12 13:31
@sp-philippe-oger 

If I can somehow help, tell me, please.

**Comment by philippe2803** [comment] 2018-07-12 15:06
There was a major issue indeed.
I rectified it. I deleted version 2 from the versions available. Version 3 should work as intended.

**Comment by oshliaer** [comment] 2018-07-12 16:18
It seems it works fine now! Thank you!

**Comment by philippe2803** [comment] 2018-07-12 16:49
Cool. Glad it works. 
Closing the issue now.

**Closed as completed by philippe2803** 2018-07-12 16:49 UTC
